const suggestions = [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "ASP.NET",
    "Responsive Design",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "UI/UX Design",
    "Web Design",
    "User Interface",
    "User Experience",
    "Bootstrap",
    "Sass",
    "Less",
    "RESTful API",
    "GraphQL",
    "Web Performance",
    "Web Accessibility",
    "Progressive Web Apps (PWA)",
    "Web Security",
    "Version Control (Git)",
    "Web Hosting",
    "Content Management Systems (CMS)",
    "eCommerce Development",
    "Mobile-First Development",
    "Cross-Browser Compatibility",
    "Web Development Tools",
    "Code Editors",
    "Responsive Images",
    "Web Animation",
    "Web Components",
    "SEO (Search Engine Optimization)",
];

export default suggestions;